apiVersion: v1
kind: Secret
metadata:
  name: {{ include "morse.fullname" . }}-secrets
  labels:
    {{- include "morse.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "morse.database.url" . | b64enc | quote }}
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  google-gemini-api-key: {{ .Values.secrets.googleGeminiApiKey | b64enc | quote }}