---
# API Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "morse.fullname" . }}-api
  labels:
    {{- include "morse.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "morse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "morse.fullname" . }}-frontend
  labels:
    {{- include "morse.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    {{- include "morse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend